services:
  app:
    build:
      context: ./docker/dev/app/build
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
      - php-fpm-socket-store:/var/run/php-fpm
  web:
    build:
      context: ./docker/dev/web/build
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/workspace
      - php-fpm-socket-store:/var/run/php-fpm
  db:
    build:
      context: ./docker/dev/db/build
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: devuser
      POSTGRES_DB: devdb
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-store:
  php-fpm-socket-store:
