services:
  db:
    build:
      context: ./docker/dev/db/build
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: devuser
      POSTGRES_DB: devdb
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: psql -c "SELECT 1" devdb devuser || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
  app:
    build:
      context: ./docker/dev/app/build
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
      - php-fpm-socket-store:/var/run/php-fpm
    depends_on:
      db:
        condition: service_healthy
  web:
    build:
      context: ./docker/dev/web/build
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/workspace
      - php-fpm-socket-store:/var/run/php-fpm
volumes:
  db-store:
  php-fpm-socket-store:
