services:
  web:
    build:
      dockerfile: ./docker/dev/web/build/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/workdir
      - php-fpm-socket-store:/var/run/php-fpm
  app:
    build:
      dockerfile: ./docker/dev/app/build/Dockerfile
    volumes:
      - ./:/workdir
      - php-fpm-socket-store:/var/run/php-fpm
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: devuser
      POSTGRES_DB: devdb
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-store:
  php-fpm-socket-store:
